### PR TITLE
Added objc inference to RVRGimbalDelegate methods

### PR DESCRIPTION
**Pull request by ajainrmn**
This fixes the following issue: https://github.com/RoverPlatform/rover-ios/issues/282.

### CODE REVIEW

**Review by seanrucker — CHANGES_REQUESTED** [review]
This looks good. Can you just bump the version number in the podspec as well? with that in place, I will issue a release. Thanks!

**Comment by ajainrmn** [comment]
@seanrucker The patch version was bumped in the commit itself (within the `Rover.podspec` file) to 1.10.3. Am I missing something?

**Comment by seanrucker** [comment]
@ajainrmn you're correct, my apologies. We need it changed in two places, I mistook the place you changed it. 

The other place it needs to be updated is here: https://github.com/RoverPlatform/rover-ios/blob/master/Rover/Serializables.swift#L246

**Comment by ajainrmn** [comment]
@seanrucker I have updated the code as requested. My Xcode remove unnecessary whitespaces from a file, I hope that is OK.

**Review by seanrucker — APPROVED** [review]

**Comment by seanrucker** [comment]
@ajainrmn 1.10.3 has been released. Thanks for your efforts on this! 🥇

**Pull request merged**
